project:
  type: website
  output-dir: docs

website:
  title: "CAV4ECO-DRIVING"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - updates.qmd
      - team.qmd
      - contact.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

