---
title: "Updates"
---

-   The PhD scholarship at USYD is no longer available.
-   We are seeking **three additional PhD students with full scholarship** to join this project: one based at UQ focusing on developing CAV-oriented control strategies using the state-of-the-art deep learning methods, one at USYD focusing on developing and testing control strategies for traffic mixed with CAV, such as real-time speed harmonisation, cooperative lane changing and ramp metering, and long-distance eco-driving, and one at QUT focusing on developing a sustainability-oriented car following model by accounting for energy consumption and emissions. The UQ position is open exclusively to domestic students, while the positions at USYD and QUT have no such restrictions. For more information about the PhD position at UQ, please contact either Prof Zuduo Zheng or A/Prof Jiwon Kim, for the PhD position at USYD, please contact Prof Michiel Bliemer, and for the PhD position at QUT, please contact Prof Lidia Morawska.
-   The first PhD scholar Mr Jiahao Zhang who will work on this DP project has joined the team.Jiahao earned his master’s degree from Zhejiang University, widely recognized as one of the top universities in China, in 2024. He completed his bachelor’s degree in 2021 through the Joint Bachelor Program between Beijing Jiaotong University and TU Delft. Jiahao is a talented young researcher with some solid research experience and a nice publication track record. He joined UQ in October 2024, and his thesis will be directly based on our DP project. Welcome on board Jiahao, and we look forward to working with you on this exciting project.
